name: Deploy Frontend
on:
  push:
    branches:
      - main # could be 'master' as well
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - run: docker build -t sameer/react-test -f Dockerfile.dev .
      - run: docker run -e CI=true sameer/react-test npm run test

      - name: Generate deployment package
        run: zip -r deploy-build.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          #  To generate access keys creatte iam user which create keys to be used by external apps
          aws_access_key: ${{secrets.AWS_ACESS_KEY}}
          aws_secret_key: ${{secrets.AWS_SECRET_KEY}}
          application_name: 'frontend'
          environment_name: 'Frontend-env'
          existing_bucket_name: elasticbeanstalk-ap-south-1-565964368607
          region: ap-south-1
          version_label: ${{ github.sha }}
          deployment_package: deploy-build.zip
